### ISSUE TITLE
fetchAs with RequestProperties.Mode RequestMode.Nocors is not working

### ISSUE THREAD

**Issue by TheDevKnight** [thoth-org/Thoth.Fetch#15]
Hi,

im very new to F# and web development. I started with the Safe Stack and try to access to an external API from my app. 

But i had problem to get a succeded call from the browser because of CORSs. 
Then i found the solution to add a RequestMode to the call 

`let getKonten() = Fetch.fetchAs<Konto list> ("http://safestacktest.azurewebsites.net/konten", [ RequestProperties.Mode RequestMode.Nocors ])`

and i see (DevConsole F12) that the call to my API works and ive got a 200 and the data.
But then a exception is raised and i have no clue what the problem is. When i try a call over local host and return the identical data it will work and i have my deserialzed data in the app.

`Fetch.fs?cbdb:353 Uncaught (in promise) Error: 0 for URL at a (Fetch.fs?cbdb:353)`

Here is my SampleApp

https://github.com/TheDevKnight/SafeStackTest

it is the clean safe template and i added only a few lines to get my objects from the services.
Can someone give me a hint what im doing wrong?

Thx for any help

Regards

**Comment by MangelMaxime** [comment]
Hello,

CORS is a security from the browser to protect you from attacks etc.

If you are trying to access a resource external to your API you need to allow the access from your server too by adding the client to the whitelisted resources.

It means that on your server hosted at `http://safestacktest.azurewebsites.net` you need to allow called from your client URL.

I don't think the problem you are facing is not due to a bug in Thoth.Fetch but more likely a problem in your configuration. You should try to search for CORS documentation. 

And also, try to get support from SAFE stack users from their repo or via the [FSSF slack](https://fsharp.org/guides/slack/).

Perhaps someone had the same problem as you have and will be able to help you.

**Comment by TheDevKnight** [comment]
you are right, but it is strange. That the network call is work but the rest not. 
The call also work, if i switch temporary to the origin server with my API. 
I will focus on CORS again, thank you for the hint with the slack channel.
