### ISSUE TITLE
Lack of compiler switch causes IDE errors?

### ISSUE THREAD

**Issue by njlr** [thoth-org/Thoth.Fetch#37]
Suppose I have a shared isomorphic library `Shared.fsproj` like this:

```fsharp
module Shared

#if FABLE_COMPILER
open Thoth.Json
#else
open Thoth.Json.Net
#endif

module Decode = 
  
  let foo = Decode.int
```

Then, using `Thoth.Fetch` with this library in `Client.fsproj` causes errors in the IDE (Ionide):

```fsharp
module Client

open Thoth.Fetch

#if FABLE_COMPILER
open Thoth.Json
#else
open Thoth.Json.Net
#endif

open Shared

let fetchFoo () = 
  Fetch.tryGet("http://localhost:5000", decoder = Decode.foo)
```

> The type 'Thoth.Json.JsonValue' is not compatible with the type 'JsonValue'F# Compiler[1](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/compiler-messages/fs0001)

Of course, compiling with Fable is fine, because then `FABLE_COMPILER` is set. 

I believe that the issue is here: https://github.com/thoth-org/Thoth.Fetch/blob/master/src/Fetch.fs#L6

Happy to send a PR!

**Comment by MangelMaxime** [comment]
Hello @njlr,
This is unfortunatly a limitation of Ionide which doesn't provide a way to set compiler directives, at least last time that I checked.

The thing is that Thoth.Fetch should only be used with Thoth.Json and never with Thoth.Json.Net because it use JavaScript API like promise / fetch which don't exist in .NET.

I don't think there is a way to work around this issue from the code side of the library.

One idea that I have is to try to set the compiler directives inside of your "client" fsproj and see if Ionide forward that to the compiler.

I believe the XML tag to do that is `DefineConstants`.

**Comment by njlr** [comment]
Changing the code in `Thoth.Fetch` from this:

```fsharp
open Thoth.Json
```

to this:

```fsharp
#if FABLE_COMPILER
open Thoth.Json
#else
open Thoth.Json.Net
#endif
```

will fix the IDE issue. 

It doesn't enable the library to work outside of a browser context, just for IDE purposes.

**Comment by njlr** [comment]
Hmmm, I hadn't considered that, but I think it might still work... 

 - In compiled .NET case, `FABLE_COMPILER` is not set so we get `open Thoth.Json.Net`
 - In Fable case, Fable takes the source-code from `/fable`, which contains the compiler switch so we get `open Thoth.Json`

**Comment by MangelMaxime** [comment]
> * In compiled .NET case, `FABLE_COMPILER` is not set so we get `open Thoth.Json.Net` (this is not valid but it wouldn't have worked anyway)

I cannot compile the project with the line `open Thoth.Json.Net` in it because `Thoth.Json.Net` is not a dependency of Thoth.Fetch.

When you do `dotnet pack` to prepare the package for NuGet there is a compilation steps which would failed in our case.

**Comment by njlr** [comment]
Ah OK that makes sense. The model I follow in my own projects is that everything that depends on `Thoth.Json` also depends on `Thoth.Json.Net` and vice-versa.

Looking forward to a universal version!
